jhipster-dev-postgresql:
  container_name: talarion2-dev-postgresql
  image: postgres
  # volumes:
  # - ~/volumes/jhipster/talarion2/dev-postgresql/:/var/lib/postgresql/
  environment:
  - POSTGRES_USER=talarion2
  - POSTGRES_PASSWORD=
  ports:
  - "5432:5432"

